### ISSUE TITLE
Programing Microcontrollers -The Embedded World!

### ISSUE THREAD

**Issue by vikrantdeveloper** [hardware-hackers-club-delhi/Talks#2]
Attaching the PDF file for my tech talk proposal in specific given format-

[Hardware Hackers TECH Talk proposal.pdf](https://github.com/hardware-hackers-club-delhi/Talks/files/3519027/Hardware.Hackers.TECH.Talk.proposal.pdf)

**Comment by ruchikabgosain** [comment]
Hey @vikrantdeveloper will you be available to deliver this talk on our next meet up on August 31?
Let us know so that we can schedule the agenda accordingly. 
Thanks

**Comment by vikrantdeveloper** [comment]
Yes I will be there .Thanks for selecting my talk proposal
