### ISSUE TITLE
Building using ESP32 | A developer first MCU

### ISSUE THREAD

**Issue by karx** [hardware-hackers-club-delhi/Talks#3]
### Abstract
ESP8266 and ESP32 is a series of low-cost, low-power system-on-chip microcontrollers with integrated Wi-Fi and dual-mode Bluetooth.
![ESP32](https://www.espressif.com/sites/default/files/modules/esp32-wroom-32-01-s.png)

### About
We shall go over the current scene of Open-Hardware/IoT ecosystem, by breaking down the session into the following segments:

* Choice of `Board`
* Choice of `Language`
* Choice of `Framework`

Along with understanding how they fit together.
### Pre-requisites

- Basic understanding of computer systems.
- Laptops + Internet connectivity

- ESP32 + LED lights 
`I would be able to bring the necessary if RSVPs < 10. `

##### Expected duration
45 mins

### Level
Any

### Resources
* https://www.exploreembedded.com/wiki/Overview_of_ESP32_features._What_do_they_practically_mean%3F
* [Micropython](https://karx.github.io/Micropython)
* [Esprunio](https://karx.github.io/Esprunio)
* [https://www.espressif.com/](https://www.espressif.com/)
* [Blog](https://akriya.co.in/esp/)

[Link to old slides here](https://docs.google.com/presentation/d/e/2PACX-1vQEtuBjZjfiMrrDJDXblN-IMoPkapX30WOQh5ke2zaNnbXdmdt16w14frvkssjF3Ri4U5ElPOenhSSw/pub?start=false&loop=false&delayms=3000&slide=id.p)

### Speaker Bio
Hi All, I am Kartik and am very glad to introduce myself to your esteemed community.

![Kartik Image](https://avatars3.githubusercontent.com/u/7826138?s=400&u=9fb2c463d89472c513d0d0f47c77218f348a0a0b&v=4)

Just after graduation in 2015, I worked for Bing Search Engine team for a couple of years and since then have been working on my own venture here in Noida. 
We work as a product house, who also provide specialized services if and when needed, in the domain of Web Technologies and IoT.

Along with me would be Ashtam Singh who can be best described as a maker, fire-fighter and an electronics lover. 
![Astham Singh Image](https://avatars3.githubusercontent.com/u/28580833?s=460&v=4)

##### Social profiles:
[Facebook](https://www.facebook.com/karx01)
[Twitter @karx_brb](https://twitter.com/karx_brb)
[Linkedin](https://www.linkedin.com/in/karx01/)
[Github karx](https://github.com/karx)
[Github ashtam](https://github.com/ashtam55)

**Comment by karx** [comment]
Great!
Ping @ashtam55. 

Have we finalized the dates for the next meetup (or whichever one we plan this in)?
I have discussed with @astham55 offline regarding the same, both Workshop and Talk sound like a great idea.

As the proposal mentions, there is a hardware requirement for attendees which is an ESP32.
I would be able to bring 5-6 of the ESP32 MCUs that I have, which could be shared if need be.

**Comment by karx** [comment]
# 2019 - Connected ecosystem | IoT Workshop

## Event Description
We shall co-host a hands-on workshop focused on developing an e2e IoT solution using ESP32, Arduino Framework and Google cloud services.

Participants will learn the basics of software systems, SoC, and build a solution for a typical use case. They will be able to build, and test the solution in class and build it back home as well.

## Schedule

| Day  | Session | Topic  | Sample |
|---|---|---|---|
| Day 0 | Part A | Registration and onboarding  | - |
| Day 0 | Part B | IoT Systems overview  | [Hardware](https://docs.google.com/presentation/d/e/2PACX-1vQEtuBjZjfiMrrDJDXblN-IMoPkapX30WOQh5ke2zaNnbXdmdt16w14frvkssjF3Ri4U5ElPOenhSSw/pub?start=false&loop=false&delayms=3000&slide=id.g3dcabb058a_1_6) + [Software]() |
| Day 0 | Part C | Our toolkit - Workshop overview | [CokeVoting](https://akriya.co.in/coke-voting-machine/) |
| Day 1 | Part   | Hands-on  workshop (with mentors to guide and help)  | - |
| Day 2 | Part A | Demo of builds by students | - |
| Day 3 | Part B | Closing | - |

 Reviews would be nice.

**Comment by iayanpahwa** [comment]
@karx are you available on 9th Dec to deliver this talk?

**Comment by iayanpahwa** [comment]
@karx, @ashtam55 this talk has been scheduled for 8th dec meet-up, see you there :)

**Comment by karx** [comment]
Awesome!

**Comment by iayanpahwa** [comment]
Thanks for the talk @karx , Please share link to slides(if any).

**Comment by karx** [comment]
Awesome experience.
* Slides Used: [Link](https://goo.gl/24u5He)
* One pager on ESP32: [Link](https://akriya.co.in/esp/)
